Adding some threat intel feeds. Tidying up timezone formatting.

diff --git a/threatinfo b/threatinfo
--- a/threatinfo
+++ b/threatinfo
@@ -187,39 +187,159 @@ function resolve_Country_Name(){
     egrep "^${1}" ${KEEP_DATA_LOCATION}/countrycodes.txt |cut -f 2- -d " "
 }
 
+function check_Alienvault_Reputation(){
+
+    # Echoes either "Not found" or the Alienvault classification.
+    alienRep=$( egrep "^${targetIP}#" ${KEEP_DATA_LOCATION}/alienvault.data |cut -f 4 -d '#' )
+
+    [ -n "$alienRep" ] && echo "$alienRep" || echo "Not found"
+}
+
+function check_BlocklistDe_Status(){
+
+    egrep -q "^${targetIP}$" ${KEEP_DATA_LOCATION}/blocklist.de && echo "Found" || echo "Not found"
+}
+
+function check_Bruteforce_Status(){
+
+    egrep -q "^${targetIP}\s" ${KEEP_DATA_LOCATION}/bruteforce.data && echo "Found" || echo "Not found"
+}
+
+function check_BadIPs_Status(){
+
+    egrep -q "^${targetIP}$" ${KEEP_DATA_LOCATION}/badips.data && echo "Found" || echo "Not found"
+}
+
+function check_CompIPs_Status(){
+
+    egrep -q "^${targetIP}$" ${KEEP_DATA_LOCATION}/compips.data && echo "Found" || echo "Not found"
+}
+
+function check_Simple_Status(){
+
+    egrep -q "^${targetIP}$" ${KEEP_DATA_LOCATION}/${1} && echo "Found" || echo "Not found"
+}
+
 function fetch_data(){
 
+    #
+    # Fetch a country code to country name mapping database. Datahub.io maintains one.
+    #
+    # We only fetch this if the existing one is > $COUNTRY_CODE_REFRESH days old, since it doesn't change often.
+    #
     if [ $( find ${KEEP_DATA_LOCATION}/countrycodes.txt -mtime -${COUNTRY_CODE_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
         echo "Freshening country code data"
 
         curl -L -s https://datahub.io/core/country-list/r/data.json |jq '.[] | "\(.Code) \(.Name)"' |sed 's/^"//; s/\"$//; ; s/Russian\ Federation/Russia/' >${KEEP_DATA_LOCATION}/countrycodes.txt 
-        echo
     fi
 
+    #
+    # Fetch the AlienVault reputation database. This is updated hourly, so we'll update our copy hourly
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/alienvault.data -mmin -60 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Alienvault reputation database"
+
+        curl -L -s https://reputation.alienvault.com/reputation.data >${KEEP_DATA_LOCATION}/alienvault.data
+    fi    
+
+    #
+    # Fetch the Blocklist.de blocklist. Update daily.
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/blocklist.de -mtime -1 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Blocklist.de database"
+
+        curl -L -s https://lists.blocklist.de/lists/all.txt >${KEEP_DATA_LOCATION}/blocklist.de
+    fi
+
+    #
+    # Fetch the Bruteforce Blocker threat feed. Update daily.
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/bruteforce.data -mtime -1 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Bruteforce Blocker database"
+
+        curl -L -s http://danger.rulez.sk/projects/bruteforceblocker/blist.php >${KEEP_DATA_LOCATION}/bruteforce.data
+    fi
+
+    #
+    # Fetch the CINS Bad IPs database. This is updated in realtime, so we'll update our copy hourly
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/badips.data -mmin -60 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening CINS Bad IPs database"
+
+        curl -L -s http://cinsscore.com/list/ci-badguys.txt >${KEEP_DATA_LOCATION}/badips.data
+    fi
+
+    #
+    # Fetch the Emerging Threats Compromised IPs database. Update daily.
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/compips.data -mtime -1 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening ET Compromised IPs database"
+
+        curl -L -s https://rules.emergingthreats.net/blockrules/compromised-ips.txt >${KEEP_DATA_LOCATION}/compips.data
+    fi
+
+    #
+    # Fetch the Darklist database. Update hourly
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/darklist.data -mmin -60 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Darklist database"
+
+        curl -L -s http://www.darklist.de/raw.php >${KEEP_DATA_LOCATION}/darklist.data
+    fi
+
+    #
+    # Fetch the Greensnow database. Update hourly
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/greensnow.data -mmin -60 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Greensnow database"
+
+        curl -L -s https://blocklist.greensnow.co/greensnow.txt >${KEEP_DATA_LOCATION}/greensnow.data
+    fi
+
+    #
+    # Fetch the Talos database. Update daily.
+    #
+    if [ $( find ${KEEP_DATA_LOCATION}/talos.data -mtime -1 2>/dev/null |wc -l ) -lt 1 ]; then
+
+        echo "Freshening Talos database"
+
+        curl -L -s http://www.talosintelligence.com/documents/ip-blacklist >${KEEP_DATA_LOCATION}/talos.data
+    fi
+
+    # 
     # The main routine that pulls data from the various data sources
+    #
+    echo
 
-    if [ ! -d ${KEEP_DATA_LOCATION}/${1} ]; then
-        mkdir -p ${KEEP_DATA_LOCATION}/${1}
+    if [ ! -d ${KEEP_DATA_LOCATION}/${targetIP} ]; then
+        mkdir -p ${KEEP_DATA_LOCATION}/${targetIP}
     fi
 
-    echo -n "Fetching data."
+    echo -n "Fetching ${targetIP} data."
 
     #
     # Fetch data from IPInfo.io. This gives really good location data.
     #
 
-    if [ $( find ${KEEP_DATA_LOCATION}/${1}/ipinfo.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
+    if [ $( find ${KEEP_DATA_LOCATION}/${targetIP}/ipinfo.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
-        IPINFO_DATA=$( curl -s "https://ipinfo.io/${1}/?token=${IPINFO_KEY}" |jq '.' )
+        IPINFO_DATA=$( curl -s "https://ipinfo.io/${targetIP}/?token=${IPINFO_KEY}" |jq '.' )
 
         if [ $KEEP_DATA -eq 1 ]; then
 
-            echo "${IPINFO_DATA}" >${KEEP_DATA_LOCATION}/${1}/ipinfo.json
+            echo "${IPINFO_DATA}" >${KEEP_DATA_LOCATION}/${targetIP}/ipinfo.json
         fi
     else
 
-        IPINFO_DATA="$( cat ${KEEP_DATA_LOCATION}/${1}/ipinfo.json )"
+        IPINFO_DATA="$( cat ${KEEP_DATA_LOCATION}/${targetIP}/ipinfo.json )"
     fi
    
     echo -n "."
@@ -238,17 +358,17 @@ function fetch_data(){
     # Fetch data from IPData.co. This provides some really useful assessments on internet scanners
     #
 
-    if [ $( find ${KEEP_DATA_LOCATION}/${1}/ipdata.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
+    if [ $( find ${KEEP_DATA_LOCATION}/${targetIP}/ipdata.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
-        IPDATA_DATA=$( curl -s "https://api.ipdata.co/${1}?api-key=${IPDATA_KEY}" |jq '.' )
+        IPDATA_DATA=$( curl -s "https://api.ipdata.co/${targetIP}?api-key=${IPDATA_KEY}" |jq '.' )
 
         if [ $KEEP_DATA -eq 1 ]; then
 
-            echo "${IPDATA_DATA}" >${KEEP_DATA_LOCATION}/${1}/ipdata.json
+            echo "${IPDATA_DATA}" >${KEEP_DATA_LOCATION}/${targetIP}/ipdata.json
         fi
     else
 
-        IPDATA_DATA="$( cat ${KEEP_DATA_LOCATION}/${1}/ipdata.json )"
+        IPDATA_DATA="$( cat ${KEEP_DATA_LOCATION}/${targetIP}/ipdata.json )"
     fi
 
     echo -n "."
@@ -262,17 +382,17 @@ function fetch_data(){
 
     if [ -n "${SHODAN_KEY}" ]; then
 
-        if [ $( find ${KEEP_DATA_LOCATION}/${1}/shodan.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
+        if [ $( find ${KEEP_DATA_LOCATION}/${targetIP}/shodan.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
-            SHODAN_DATA=$( curl -s "https://api.shodan.io/shodan/host/${1}?key=${SHODAN_KEY}" |jq '.')
+            SHODAN_DATA=$( curl -s "https://api.shodan.io/shodan/host/${targetIP}?key=${SHODAN_KEY}" |jq '.')
 
             if [ $KEEP_DATA -eq 1 ]; then
 
-                echo "${SHODAN_DATA}" >${KEEP_DATA_LOCATION}/${1}/shodan.json
+                echo "${SHODAN_DATA}" >${KEEP_DATA_LOCATION}/${targetIP}/shodan.json
             fi
         else
 
-            SHODAN_DATA="$( cat ${KEEP_DATA_LOCATION}/${1}/shodan.json )"
+            SHODAN_DATA="$( cat ${KEEP_DATA_LOCATION}/${targetIP}/shodan.json )"
         fi
 
         echo -n "."
@@ -284,17 +404,17 @@ function fetch_data(){
     # This gives good analysis from their honeypots.
     #
 
-    if [ $( find ${KEEP_DATA_LOCATION}/${1}/greynoise.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
+    if [ $( find ${KEEP_DATA_LOCATION}/${targetIP}/greynoise.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
-        GREYNOISE_DATA=$( curl -s  https://api.greynoise.io/v3/community/${1} |jq '.' )
+        GREYNOISE_DATA=$( curl -s  https://api.greynoise.io/v3/community/${targetIP} |jq '.' )
 
         if [ $KEEP_DATA -eq 1 ]; then
 
-            echo "${GREYNOISE_DATA}" >${KEEP_DATA_LOCATION}/${1}/greynoise.json
+            echo "${GREYNOISE_DATA}" >${KEEP_DATA_LOCATION}/${targetIP}/greynoise.json
         fi
     else
 
-        GREYNOISE_DATA="$( cat ${KEEP_DATA_LOCATION}/${1}/greynoise.json )"
+        GREYNOISE_DATA="$( cat ${KEEP_DATA_LOCATION}/${targetIP}/greynoise.json )"
     fi
 
     echo -n "."
@@ -305,7 +425,7 @@ function fetch_data(){
     # Since this gets updated in realtime we're not going to use cached values for this data set.
     #
 
-    ABUSEIPDB_DATA=$( curl -s -H "Key: ${ABUSEIPDB_KEY}" -H "Accept: application/json" "https://api.abuseipdb.com/api/v2/check?ipAddress=${1}&maxAgeInDays=90" |jq '.' )
+    ABUSEIPDB_DATA=$( curl -s -H "Key: ${ABUSEIPDB_KEY}" -H "Accept: application/json" "https://api.abuseipdb.com/api/v2/check?ipAddress=${targetIP}&maxAgeInDays=90" |jq '.' )
 
     echo -n "."
     
@@ -313,17 +433,17 @@ function fetch_data(){
     # Fetch WHOIS data in JSON format using RDAP
     #
 
-    if [ $( find ${KEEP_DATA_LOCATION}/${1}/whois.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
+    if [ $( find ${KEEP_DATA_LOCATION}/${targetIP}/whois.json -mtime -${IP_DATA_REFRESH} 2>/dev/null |wc -l ) -lt 1 ]; then
 
-        WHOIS_DATA=$( curl -s -L -H "Accept: application/json" "https://rdap.apnic.net/ip/${1}/32" |jq '.' )
+        WHOIS_DATA=$( curl -s -L -H "Accept: application/json" "https://rdap.apnic.net/ip/${targetIP}/32" |jq '.' )
 
         if [ $KEEP_DATA -eq 1 ]; then
 
-            echo "${WHOIS_DATA}" >${KEEP_DATA_LOCATION}/${1}/whois.json
+            echo "${WHOIS_DATA}" >${KEEP_DATA_LOCATION}/${targetIP}/whois.json
         fi
     else
 
-        WHOIS_DATA="$( cat ${KEEP_DATA_LOCATION}/${1}/whois.json )"
+        WHOIS_DATA="$( cat ${KEEP_DATA_LOCATION}/${targetIP}/whois.json )"
     fi
 
     echo "."
@@ -374,15 +494,24 @@ function parse_fields() {
     abuseReporters=$( get_AbuseIPDB_Field numDistinctUsers )
     abuseConfidence=$( get_AbuseIPDB_Field abuseConfidenceScore )
     abuseConnType=$( get_AbuseIPDB_Field usageType )
+
+    alienVaultStatus=$( check_Alienvault_Reputation )
+    blocklistDeStatus=$( check_Simple_Status blocklist.de )
+    bruteforceStatus=$( check_Bruteforce_Status )
+    badIPsStatus=$( check_Simple_Status badips.data )
+    compIPsStatus=$( check_Simple_Status compips.data )
+    darklistStatus=$( check_Simple_Status darklist.data )
+    greensnowStatus=$( check_Simple_Status greensnow.data )
+    talosStatus=$( check_Simple_Status talos.data )
 }
     
 function report(){
 
-    underline "$1"
+    underline "${targetIP}"
 
     if [ "${bogon}" == "true" ]; then
 
-        echo -e "\n${1} is a non-routable address. No data available.\n\n"
+        echo -e "\n${targetIP} is a non-routable address. No data available.\n\n"
         return
     fi
     
@@ -454,7 +583,7 @@ function report(){
     Timezone Info
     ============="
 
-    if [ "${timeZoneIpinfo}" == "${timeZoneIpdata}" -a "${UTCOffsetIpinfo}" == "${UTCOffsetIpdata}" -a "${currentTimeIpinfo}" == "${currentTimeIpdata}" ]; then
+    if [ "${timeZoneIpinfo}" == "${timeZoneIpdata}" -a "${UTCOffsetIpinfo}" == "${UTCOffsetIpdata}" ]; then
 
         echo "
     Timezone:                 ${timeZoneIpinfo}
@@ -466,15 +595,15 @@ function report(){
         echo "
     IPInfo.io:
    
-        Timezone:                 ${timeZoneIpinfo}
-        UTC offset:               ${UTCOffsetIpinfo}
-        Current time:             ${currentTimeIpinfo}
+        Timezone:             ${timeZoneIpinfo}
+        UTC offset:           ${UTCOffsetIpinfo}
+        Current time:         ${currentTimeIpinfo}
 
     IPData.co:
 
-        Timezone:                 ${timeZoneIpdata}
-        UTC offset:               ${UTCOffsetIpdata}
-        Current time:             ${currentTimeIpdata}"
+        Timezone:             ${timeZoneIpdata}
+        UTC offset:           ${UTCOffsetIpdata}
+        Current time:         ${currentTimeIpdata}"
 
     fi
 
@@ -510,7 +639,19 @@ function report(){
     Reports past 90d:         $abuseReports
     No. of reporters:         $abuseReporters
     Confidence of abuse:      ${abuseConfidence}%
-    Link:                     https://abuseipdb.com/check/${1}
+    Link:                     https://abuseipdb.com/check/${targetIP}
+
+    Threat Intel Feeds
+    ==================
+
+    AlienVault:               ${alienVaultStatus}
+    Blocklist.de:             ${blocklistDeStatus}
+    Brute Force Blocklist:    ${bruteforceStatus}
+    CINS Bad IPs:             ${badIPsStatus}
+    Darklist:                 ${darklistStatus}
+    ET Compromised IPs:       ${compIPsStatus}
+    Greensnow Blocklist:      ${greensnowStatus}
+    Talos Blocklist:          ${talosStatus}
 "
 
 }
@@ -520,10 +661,11 @@ main() {
     # Currently this is only tested for IPv4 IPs.
     # Check that there's a $1, and that it's an IPv4 IP
     check_arg "${1}"
+    targetIP=${1}
     get_keys
-    fetch_data "${1}"
+    fetch_data
     parse_fields
-    report "${1}"
+    report
 }
 
 main "${1}"
